export interface Category {
  id: string;
  label: string;
  groups: string[];
}

export interface CategoryGroup {
  label: string;
  description: string;
}

// Canonical task families can have several parents. Domains are not exclusive professions.
const groups = {
  'software development': [
    'Web development', 'Mobile development', 'Desktop development', 'Backend development',
    'API design', 'Code review', 'Debugging', 'Code refactoring',
    'Programming languages', 'Package development', 'Frontend architecture', 'Full-stack development',
    'Software architecture', 'Domain-driven design', 'Event-driven architecture', 'Distributed systems',
    'Microservices', 'Concurrency and asynchronous programming', 'State management', 'Component libraries',
    'Command-line applications', 'Developer tooling', 'Build systems', 'Dependency management',
    'Monorepo management', 'Code generation', 'Type modeling', 'Serialization and data formats',
    'Search implementation', 'Caching strategies', 'Real-time applications', 'Offline application support',
    'Internationalized application development', 'Payment integration', 'Third-party API integration', 'Browser extensions',
    'Desktop application packaging', 'Application migrations', 'Legacy modernization', 'Application profiling',
    'Memory management', 'Algorithm design', 'Version control workflows', 'Release engineering',
    'Technical documentation generation',
  ],
  'software testing and quality': [
    'Software unit testing', 'Software integration testing', 'Software end-to-end testing', 'Browser testing',
    'Software performance testing', 'Accessibility testing', 'Test-driven development', 'Static code analysis',
    'Software compatibility testing', 'Software quality assurance', 'Software regression testing', 'Software load testing',
    'Software stress testing', 'Software security testing', 'Software contract testing', 'Mutation testing',
    'Property-based testing', 'Fuzz testing', 'Snapshot testing', 'Visual regression testing',
    'Mobile application testing', 'Cross-browser testing', 'Software test fixtures and test data', 'Software test mocking',
    'Test coverage analysis', 'Flaky test diagnosis', 'Test automation architecture', 'Software acceptance testing',
    'Software exploratory testing', 'Database testing', 'API testing', 'Localization testing',
    'Software test environment setup', 'Software release validation', 'Code formatting and linting',
  ],
  'infrastructure and operations': [
    'Cloud infrastructure', 'Containers', 'Kubernetes', 'Continuous integration',
    'Software deployment', 'Linux administration', 'Windows administration', 'macOS administration',
    'Networking', 'Infrastructure monitoring and incident response', 'Infrastructure as code', 'Server provisioning',
    'Configuration management', 'Serverless operations', 'Edge deployments', 'Continuous delivery',
    'GitOps', 'Container image optimization', 'Container registries', 'Service meshes',
    'Reverse proxies', 'Load balancing', 'DNS administration', 'TLS certificate management',
    'SSH administration', 'Storage administration', 'Virtual machines', 'Hypervisor administration',
    'Disaster recovery', 'Site reliability engineering', 'Observability', 'Log analysis',
    'Distributed tracing', 'Capacity planning', 'Cloud cost management', 'Secrets management',
    'Infrastructure migrations', 'Software package publishing', 'Homelab administration', 'Remote workspace administration',
  ],
  'security and privacy': [
    'Cybersecurity audits', 'Threat modeling', 'Vulnerability analysis', 'Security remediation',
    'Authentication', 'Authorization', 'Cryptography', 'Privacy assessment',
    'Compliance assessment', 'Digital forensics', 'Application security', 'API security',
    'Web security', 'Mobile security', 'Cloud security', 'Container security',
    'Network security', 'Identity and access management', 'OAuth integration', 'Single sign-on',
    'Session security', 'Dependency security', 'Software supply chain security', 'Secrets detection',
    'Penetration testing', 'Security policy design', 'Security incident response', 'Security monitoring',
    'Security testing automation', 'Abuse prevention', 'Data anonymization', 'Data retention policy',
    'Privacy engineering', 'Security architecture review', 'Vulnerability disclosure', 'Security fix verification',
    'Malware analysis', 'Secure coding', 'Security awareness training',
  ],
  'data engineering': [
    'Database design', 'SQL queries', 'Data migrations', 'Data pipelines',
    'Data integration', 'Data cleaning', 'Data validation', 'Web scraping',
    'Data warehouses', 'Backup and recovery', 'Database indexing', 'Query optimization',
    'Database administration', 'Database replication', 'Database sharding', 'Database transactions',
    'Schema evolution', 'Data modeling', 'ETL and ELT', 'Stream processing',
    'Event ingestion', 'Data lakes', 'Data catalogs', 'Data lineage',
    'Data governance', 'Master data management', 'Entity resolution', 'Data deduplication',
    'Data quality monitoring', 'Data synchronization', 'Data export', 'File format conversion',
    'Document indexing', 'Search indexing', 'Vector databases', 'Dataset preparation',
    'Data access control', 'Data orchestration',
  ],
  'data analysis': [
    'Statistical analysis', 'Data visualization', 'Business intelligence', 'Product analytics',
    'Experiment analysis', 'Forecasting', 'Geospatial analysis', 'Time-series analysis',
    'Survey analysis', 'Exploratory data analysis', 'Descriptive statistics', 'Hypothesis testing',
    'Causal inference', 'Bayesian analysis', 'Regression analysis', 'Classification analysis',
    'Clustering analysis', 'Anomaly detection', 'Cohort analysis', 'Funnel analysis',
    'Retention analysis', 'Customer segmentation', 'Attribution analysis', 'Pricing analysis',
    'Financial analytics', 'Operational analytics', 'Sports analytics', 'Text analytics',
    'Network analysis', 'Scientific visualization', 'Dashboard creation', 'Interactive visualization',
    'Chart selection', 'Data storytelling', 'Metric definition', 'Experiment design',
    'A/B test evaluation', 'Sensitivity analysis',
  ],
  'AI and automation': [
    'Machine learning', 'AI model evaluation', 'Prompt engineering', 'AI agent workflows',
    'Natural language processing', 'Computer vision', 'Speech recognition', 'Robotic process automation',
    'Workflow automation', 'Model deployment', 'Deep learning', 'Reinforcement learning',
    'Recommendation systems', 'Retrieval-augmented generation', 'Semantic search', 'Embeddings',
    'AI tool integration', 'Agent orchestration', 'Agent memory', 'Model fine-tuning',
    'Model quantization', 'Inference optimization', 'AI safety evaluation', 'AI red teaming',
    'Dataset labeling', 'Synthetic data generation', 'AI benchmark design', 'Structured data extraction',
    'Document understanding', 'Optical character recognition', 'Multimodal pipelines', 'Text classification',
    'Sentiment analysis', 'Text summarization', 'Translation systems', 'Speech synthesis',
    'Automated browser workflows', 'Desktop automation', 'Email automation', 'Scheduled automation',
    'Human review workflows', 'Knowledge graphs',
  ],
  'documents and office work': [
    'Presentations', 'Word documents', 'PDF documents', 'Spreadsheets',
    'Document templates', 'Document conversion', 'Document extraction', 'Document formatting',
    'Forms and questionnaires', 'Meeting notes', 'Slide layout', 'Slide storytelling',
    'Speaker notes', 'Presentation accessibility', 'Presentation charts', 'Document styles',
    'Document redlining', 'Document commenting', 'Document comparison', 'Document accessibility',
    'Document pagination', 'Tables of contents', 'Mail merge', 'Spreadsheet formulas',
    'Spreadsheet charts', 'Spreadsheet pivots', 'Spreadsheet automation', 'Spreadsheet auditing',
    'Spreadsheet modeling', 'CSV processing', 'PDF form filling', 'PDF annotations',
    'PDF layout verification', 'PDF generation', 'PDF text extraction', 'Document scanning workflows',
    'Electronic signatures', 'LaTeX documents', 'Reports', 'Proposals',
    'Standard operating procedures', 'Minutes and action items',
  ],
  'writing and languages': [
    'Technical writing', 'Creative writing', 'Editing and proofreading', 'Translation',
    'Localization', 'Journalism', 'Academic writing', 'Grant writing',
    'Resume writing', 'Screenwriting', 'Business writing', 'UX writing',
    'API documentation', 'Release notes', 'Documentation maintenance', 'Style guides',
    'Fact checking', 'Citation checking', 'Plain-language rewriting', 'Persuasive writing',
    'Newsletter writing', 'Speechwriting', 'Interview writing', 'Biographical writing',
    'Poetry', 'Fiction plotting', 'Character development', 'Dialogue writing',
    'Worldbuilding', 'Content adaptation', 'Transcreation', 'Terminology management',
    'Multilingual editing', 'Subtitling translation', 'Technical translation', 'Scientific editing',
    'Peer review writing', 'Research abstracts', 'Executive summaries', 'Writing coaching',
  ],
  'visual design': [
    'Graphic design', 'Brand identity', 'Typography', 'Illustration',
    'Icon design', 'Logo design', 'Color systems', 'Visual hierarchy',
    'Page composition', 'Editorial design', 'Publication design', 'Poster design',
    'Infographic design', 'Print production', 'Packaging design', 'Art direction',
    'Mood boards', 'Style exploration', 'Illustration systems', 'Visual storytelling',
    'Brand guidelines', 'Brand strategy', 'Campaign design', 'Social media graphics',
    'Presentation visual identity', 'Environmental graphics', 'Signage design', 'Wayfinding',
    'Data graphic design',
  ],
  'images and photography': [
    'Image generation', 'Image editing', 'Photo retouching', 'Photography',
    'Image compositing', 'Color correction', 'Vector graphics', 'Pixel art',
    'Texture creation', 'Image optimization', 'Product photography', 'Portrait photography',
    'Landscape photography', 'Architectural photography', 'Photo selection', 'Photo restoration',
    'Background removal', 'Object removal', 'Image upscaling', 'Image segmentation',
    'Image masking', 'Digital painting', 'Concept art', 'Character illustration',
    'Sprite creation', 'Photo color grading', 'Camera setup', 'Lighting setup',
    'Image metadata management', 'Image format conversion', 'Image batch processing', 'Visual asset cataloging',
    'Photo asset delivery',
  ],
  'video and animation': [
    'Video editing', 'Animation', 'Motion graphics', 'Video rendering',
    'Subtitles and captions', 'Video production', 'Storyboarding', 'Visual effects',
    'Video encoding', 'Livestream production', 'Character animation', 'Facial animation',
    'Stop-motion animation', 'Animation timing', 'Keyframe animation', 'Procedural animation',
    'Animated interface assets', 'Video color grading', 'Video compositing', 'Video stabilization',
    'Video transitions', 'Video audio synchronization', 'Video scripting', 'Explainer videos',
    'Product demo videos', 'Screen recordings', 'Short-form videos', 'Video localization',
    'Video accessibility', 'Video asset management', 'Video quality analysis', 'Video publishing',
    'Motion tracking', 'Animation retargeting',
  ],
  '3D and spatial design': [
    '3D modeling', '3D rendering', '3D sculpting', 'Rigging',
    'Procedural geometry', 'CAD modeling', 'Architectural visualization', 'Virtual reality',
    'Augmented reality', '3D topology', 'UV mapping', '3D texturing',
    '3D materials and shaders', '3D lighting', 'Scene composition', 'Camera animation',
    'Physics simulation', 'Fluid simulation', 'Particle systems', 'Cloth simulation',
    'Hair and fur grooming', 'Character modeling', 'Environment modeling', 'Hard-surface modeling',
    'Retopology', '3D asset optimization', '3D asset conversion', 'Photogrammetry',
    '3D scanning', '3D animation workflows', 'Procedural materials', '3D compositing',
    'Building information modeling', 'Parametric modeling', 'Mesh repair', '3D product visualization',
    'Spatial interaction design',
  ],
  'audio and music': [
    'Audio editing', 'Music composition', 'Audio mixing', 'Audio mastering',
    'Sound design', 'Podcast production', 'Voice synthesis', 'Audio transcription',
    'Music notation', 'Instrument practice', 'Music arrangement', 'Songwriting',
    'Orchestration', 'Harmony analysis', 'Rhythm training', 'Ear training',
    'MIDI programming', 'Virtual instrument programming', 'Audio synthesis', 'Field recording',
    'Dialogue editing', 'Noise reduction', 'Audio restoration', 'Loudness normalization',
    'Spatial audio', 'Game audio', 'Film scoring', 'Jingle production',
    'Sample creation', 'Sample library management', 'Audio format conversion', 'Audio quality analysis',
    'Audio accessibility', 'Live sound engineering',
  ],
  'games and interactive media': [
    'Game design', 'Game development', 'Game mechanics', 'Level design',
    'Game assets', 'Game testing', 'Interactive fiction', 'Simulation design',
    'Tabletop games', 'Game modding', 'Combat design', 'Game economy design',
    'Progression design', 'Quest design', 'Narrative game design', 'Game balancing',
    'Game monetization', 'Game accessibility', 'Game UI design', 'Game AI',
    'Pathfinding', 'Physics-based gameplay', 'Multiplayer networking', 'Game server operations',
    'Procedural level generation', 'Game optimization', 'Save systems', 'Input handling',
    'Game localization', 'Game analytics', 'Interactive installation design', 'Educational simulation',
    'Serious games', 'Game production planning', 'Game publishing',
  ],
  'marketing and sales': [
    'Marketing strategy', 'Copywriting', 'Search engine optimization', 'Keyword research',
    'Content marketing', 'Social media marketing', 'Advertising', 'Sales outreach',
    'Product positioning', 'Conversion optimization', 'Market research', 'Audience research',
    'Competitive analysis', 'Brand messaging', 'Go-to-market strategy', 'Demand generation',
    'Lead generation', 'Landing page copy', 'Email campaigns', 'Lifecycle marketing',
    'Marketing automation', 'Search advertising', 'Social advertising', 'Ad creative testing',
    'Affiliate marketing', 'Influencer marketing', 'Community marketing', 'Public relations',
    'Media pitching', 'Marketing measurement', 'Marketing attribution', 'Content strategy',
    'Content calendars', 'Content distribution', 'Technical SEO', 'Local SEO',
    'International SEO', 'Link building', 'Sales qualification', 'Sales discovery',
    'Sales proposals', 'Sales negotiation', 'Account planning', 'Sales coaching',
    'Customer retention marketing',
  ],
  'business and management': [
    'Business planning', 'Project management', 'Product management', 'Process improvement',
    'Customer support', 'Human resources', 'Recruiting', 'Procurement',
    'Entrepreneurship', 'Operations planning', 'Product discovery', 'Product roadmaps',
    'Requirements analysis', 'User story writing', 'Backlog management', 'Sprint planning',
    'Agile coaching', 'Stakeholder management', 'Business process mapping', 'Service design',
    'Strategy development', 'Competitive strategy', 'Business model design', 'OKR planning',
    'KPI planning', 'Change management', 'Team leadership', 'Performance management',
    'Employee onboarding', 'Workforce planning', 'Interview design', 'Vendor evaluation',
    'Supply chain planning', 'Inventory management', 'Demand planning', 'Customer success',
    'Support knowledge bases', 'Support ticket triage', 'Customer feedback analysis', 'Partnership planning',
    'Meeting facilitation', 'Business continuity planning',
  ],
  'finance and accounting': [
    'Bookkeeping', 'Financial reporting', 'Budgeting', 'Financial modeling',
    'Tax preparation', 'Investment research', 'Valuation', 'Financial risk analysis',
    'Billing and invoicing', 'Expense management', 'Accounts payable', 'Accounts receivable',
    'Bank reconciliation', 'Cash flow planning', 'Cost accounting', 'Management accounting',
    'Audit preparation', 'Financial controls', 'Financial statement analysis', 'Financial consolidation',
    'Payroll accounting', 'Revenue recognition', 'Subscription accounting', 'Credit analysis',
    'Portfolio analysis', 'Asset allocation', 'Retirement planning', 'Insurance analysis',
    'Fundraising planning', 'Capital budgeting', 'Scenario modeling', 'Treasury management',
    'Pricing models', 'Unit economics', 'Fraud analysis', 'Financial data reconciliation',
    'Accounting document extraction',
  ],
  'law and governance': [
    'Legal research', 'Contract drafting', 'Contract review', 'Policy drafting',
    'Regulatory research', 'Corporate governance', 'Intellectual property', 'Dispute documentation',
    'Public administration', 'Records management', 'Privacy law research', 'Employment law research',
    'Commercial law research', 'Property law research', 'Consumer law research', 'Corporate law research',
    'Court filing preparation', 'Case law analysis', 'Legal correspondence', 'Legal document extraction',
    'Legal citation verification', 'Contract clause analysis', 'Contract negotiation support', 'Terms of service drafting',
    'Privacy notice drafting', 'Data processing agreements', 'Governance documentation', 'Board meeting preparation',
    'Public policy analysis', 'Policy impact assessment', 'Regulatory compliance mapping', 'Compliance evidence collection',
    'Freedom of information requests', 'Document retention planning', 'Legal translation', 'Due diligence documentation',
  ],
  'science and research': [
    'Literature reviews', 'Research design', 'Mathematics', 'Physics',
    'Chemistry', 'Biology', 'Astronomy', 'Environmental science',
    'Reproducible research', 'Scientific computing', 'Probability theory', 'Linear algebra',
    'Calculus', 'Optimization theory', 'Numerical methods', 'Differential equations',
    'Discrete mathematics', 'Symbolic mathematics', 'Experimental design', 'Research data management',
    'Scientific reproducibility', 'Research software engineering', 'Simulation modeling', 'Computational physics',
    'Computational chemistry', 'Molecular modeling', 'Bioinformatics', 'Genomics',
    'Proteomics', 'Ecology', 'Climate science', 'Earth science',
    'Oceanography', 'Meteorology', 'Remote sensing', 'Epidemiology',
    'Neuroscience', 'Psychology research', 'Econometrics', 'Qualitative research',
    'Evidence synthesis', 'Meta-analysis', 'Research ethics', 'Lab protocols',
    'Laboratory data analysis', 'Scientific instrument workflows',
  ],
  'engineering and hardware': [
    'Mechanical engineering', 'Electrical engineering', 'Electronics', 'Embedded systems',
    'Robotics', '3D printing', 'Manufacturing', 'Materials engineering',
    'Civil engineering', 'Hardware troubleshooting', 'Circuit design', 'PCB design',
    'Signal processing', 'Control systems', 'Firmware development', 'Hardware prototyping',
    'Sensor integration', 'Motor control', 'Industrial automation', 'Power systems',
    'Battery systems', 'Thermal analysis', 'Finite element analysis', 'Structural analysis',
    'Fluid dynamics', 'Mechanical tolerancing', 'Engineering drawings', 'Product manufacturability',
    'CNC programming', 'Computer-aided manufacturing', 'Manufacturing quality control', 'Maintenance planning',
    'Reliability engineering', 'Systems engineering', 'Technical specification writing', 'Hardware validation',
    'Radio frequency engineering', 'Internet of things systems', 'Digital fabrication',
  ],
  'health and wellbeing': [
    'Medical research', 'Clinical documentation', 'Nutrition', 'Fitness planning',
    'Mental wellbeing', 'Public health', 'Healthcare administration', 'Care planning',
    'Sports training', 'Health education', 'Medical literature analysis', 'Clinical trial analysis',
    'Clinical research protocols', 'Medical coding', 'Medical terminology', 'Health record organization',
    'Patient communication', 'Patient education', 'Medication information research', 'Care coordination',
    'Practice management', 'Healthcare quality improvement', 'Healthcare data analysis', 'Health service planning',
    'Nutrition research', 'Meal planning', 'Exercise programming', 'Strength training',
    'Mobility training', 'Sports performance analysis', 'Sleep planning', 'Wellbeing journaling',
    'Habit formation', 'Stress management education', 'First aid education', 'Health accessibility',
    'Population health analysis', 'Health policy analysis',
  ],
  'education and learning': [
    'Lesson planning', 'Tutoring', 'Learning materials', 'Assessment design',
    'Curriculum design', 'Language learning', 'Study planning', 'Instructional design',
    'Educational games', 'Learning evaluation', 'Course design', 'E-learning development',
    'Learning objectives', 'Rubric creation', 'Quiz creation', 'Exam preparation',
    'Feedback generation', 'Classroom activities', 'Workshop design', 'Training needs analysis',
    'Corporate training', 'Skills assessment', 'Learning analytics', 'Accessible learning materials',
    'Adaptive learning', 'Study notes', 'Flashcard creation', 'Spaced repetition planning',
    'Reading comprehension', 'Mathematical tutoring', 'Science tutoring', 'Programming tutoring',
    'Essay feedback', 'Teacher planning', 'Educational research', 'Academic advising',
    'Learning platform administration', 'Student progress tracking',
  ],
  'personal planning and communication': [
    'Travel planning', 'Event planning', 'Personal organization', 'Personal scheduling',
    'Email management', 'Public speaking', 'Negotiation', 'Career planning',
    'Decision support', 'Relationship communication', 'Personal budgeting', 'Personal goal planning',
    'Task prioritization', 'Calendar coordination', 'Time management', 'Inbox triage',
    'Email drafting', 'Invitation writing', 'Conflict resolution communication', 'Interview preparation',
    'Job search planning', 'Professional networking', 'Personal knowledge management', 'Note organization',
    'Decision journaling', 'Relocation planning', 'Travel itinerary creation', 'Travel logistics',
    'Group travel coordination', 'Wedding planning', 'Celebration planning', 'Household planning',
    'Family coordination', 'Shopping research', 'Comparison shopping', 'Volunteer coordination',
  ],
  'culture and humanities': [
    'History', 'Philosophy', 'Literary analysis', 'Art history',
    'Religious studies', 'Sociology', 'Anthropology', 'Political science',
    'Cultural research', 'Genealogy', 'Archives research', 'Oral history',
    'Historical source analysis', 'Museum interpretation', 'Exhibition planning', 'Cultural heritage documentation',
    'Musicology', 'Film criticism', 'Media studies', 'Rhetorical analysis',
    'Linguistics', 'Ethnographic research', 'Urban studies', 'International relations research',
    'Public opinion research', 'Ethics analysis', 'Logic', 'Aesthetics',
    'Folklore research', 'Archaeology', 'Classical studies', 'Digital humanities',
    'Textual criticism', 'Cultural translation', 'Humanities teaching', 'Heritage conservation planning',
  ],
  'practical and outdoor activities': [
    'Cooking', 'Gardening', 'Agriculture', 'Home improvement',
    'Crafts', 'Woodworking', 'Vehicle maintenance', 'Outdoor recreation',
    'Animal care', 'Real estate planning', 'Recipe development', 'Baking',
    'Food preservation', 'Menu planning', 'Food safety education', 'Plant identification',
    'Landscape gardening', 'Soil management', 'Irrigation planning', 'Crop planning',
    'Sustainable agriculture', 'Animal husbandry', 'Pet training', 'Pet care planning',
    'Wildlife observation', 'Camping planning', 'Hiking planning', 'Fishing planning',
    'Cycling maintenance', 'Home repair planning', 'Home energy planning', 'Home organization',
    'Furniture restoration', 'Metalworking', 'Pottery', 'Sewing',
    'Knitting and crochet', 'Leatherworking', 'Jewelry making', 'Estate planning logistics',
    'Property maintenance', 'Real estate market research', 'Farm operations planning',
  ],
  'UI and interaction design': [
    'User interface design', 'UI component design', 'Responsive interface design', 'Adaptive interface design',
    'Interaction design', 'Web interface design', 'Mobile interface design', 'Desktop interface design',
    'Dashboard design', 'Landing page design', 'Navigation design', 'Form design',
    'Search interface design', 'Table and data-grid design', 'Chart interface design', 'Settings interface design',
    'Authentication flow design', 'Checkout interface design', 'Onboarding interface design', 'Empty state design',
    'Loading state design', 'Error state design', 'Notification design', 'Modal and dialog design',
    'Touch interaction design', 'Keyboard interaction design', 'Gesture design', 'Microinteraction design',
    'Interface motion design', 'Interaction prototyping', 'Wireframes and prototypes', 'High-fidelity prototyping',
    'Visual interface audits', 'UI redesign', 'UI design handoff', 'Interface layout',
    'Interface spacing', 'Interface color contrast', 'Dark mode design', 'Design-to-code implementation',
  ],
  'UX research and design': [
    'User experience design', 'User research', 'User interviews', 'Usability testing',
    'Heuristic evaluation', 'Cognitive walkthroughs', 'Journey mapping', 'Experience mapping',
    'Persona development', 'Empathy mapping', 'Jobs-to-be-done research', 'Contextual inquiry',
    'Diary studies', 'Card sorting', 'Tree testing', 'Information architecture',
    'Task analysis', 'User flow design', 'Content design', 'Content architecture',
    'UX research planning', 'Research participant recruitment', 'Research synthesis', 'Research repository management',
    'UX metrics', 'UX benchmarking', 'UX audits', 'UX strategy',
    'UX prioritization', 'Inclusive experience design', 'Cross-channel experience design', 'Conversational experience design',
    'Voice interface design', 'Trust and consent design', 'UX experiment planning', 'Research insight communication',
  ],
  'design systems and accessibility': [
    'Design systems', 'Design tokens', 'Design system governance', 'Design system documentation',
    'Component API design', 'Component variants', 'Component accessibility', 'Design component inventory',
    'Design system migration', 'Design library maintenance', 'Accessible interaction design', 'Accessibility audits',
    'WCAG remediation', 'Keyboard navigation design', 'Focus management design', 'Screen reader experience design',
    'Reduced motion design', 'Accessible form design', 'Accessible data visualization', 'Color-independent communication',
    'Accessible typography', 'Accessible multimedia design', 'Assistive technology testing', 'Accessibility acceptance criteria',
  ],
  'physical design': [
    'Industrial design', 'Product form design', 'Ergonomic design', 'Furniture design',
    'Interior design', 'Architectural design', 'Landscape design', 'Exhibition design',
    'Retail space design', 'Stage design', 'Lighting design', 'Fashion design',
    'Textile design', 'Pattern making', 'Sustainable product design', 'Physical product prototyping',
    'Public space design', 'Universal physical access design',
  ],
  'physical product testing and quality': [
    'Physical prototype validation', 'Physical component testing', 'Physical assembly integration testing', 'Physical product performance testing',
    'Physical product durability testing', 'Mechanical fatigue testing', 'Vibration testing', 'Shock and drop testing',
    'Thermal cycling testing', 'Environmental chamber testing', 'Humidity testing', 'Corrosion testing',
    'Ingress protection testing', 'Chemical compatibility testing', 'Electromagnetic compatibility testing', 'Electrical safety testing',
    'Battery safety testing', 'Battery cycle life testing', 'Product material characterization', 'Mechanical dimensional verification',
    'Physical product safety testing', 'Physical product compliance testing', 'Physical product lifecycle testing', 'Physical product acceptance testing',
    'Physical product test fixtures', 'Laboratory test instrumentation', 'Physical product field trials', 'Accelerated life testing',
    'Physical product failure analysis', 'Physical product reliability testing', 'Physical product test planning', 'Physical product test automation',
  ],
  'manufacturing quality': [
    'Statistical process control', 'Manufacturing process validation', 'Production inspection planning', 'Incoming material inspection',
    'Supplier quality management', 'Manufacturing sampling plans', 'Measurement system analysis', 'Gauge repeatability and reproducibility',
    'Production metrology', 'Non-destructive testing', 'Destructive material testing', 'First article inspection',
    'Production acceptance testing', 'Manufacturing defect analysis', 'Root cause and corrective action', 'Manufacturing failure mode analysis',
    'Control plan development', 'Manufacturing process capability', 'Manufacturing quality audits', 'Manufacturing traceability',
    'Production quality documentation', 'Manufacturing quality systems', 'Production yield improvement', 'Lean manufacturing quality',
    'Manufacturing mistake proofing',
  ],
} as const;

type GroupLabel = keyof typeof groups;
type CategoryLabel = typeof groups[GroupLabel][number];

const descriptions: Record<GroupLabel, string> = {
  'software development': 'Creating, changing or understanding software, including application architecture, coding, developer tools, and software test implementation.',
  'software testing and quality': 'Evaluating software, firmware or digital application behavior, including automated code tests, browser tests, regressions and code quality. Physical durability and factory inspection are separate domains.',
  'infrastructure and operations': 'Deploying and operating computing systems, networks, cloud services, storage, observability and incident response for IT infrastructure.',
  'security and privacy': 'Cybersecurity, digital identity, access control, software vulnerabilities, cryptography, and protection or governance of personal data.',
  'data engineering': 'Structuring, storing, moving, integrating and maintaining datasets, databases and data infrastructure; includes data quality and recovery.',
  'data analysis': 'Interpreting data through statistics, experiments, forecasts, metrics, charts and analytical models, including scientific, financial, health and manufacturing data.',
  'AI and automation': 'Building or evaluating machine learning, language and vision systems, agent workflows, structured extraction and automated processes.',
  'documents and office work': 'Creating, editing, formatting, extracting or checking documents, presentations, PDFs, spreadsheets, forms and office artifacts in any subject.',
  'writing and languages': 'Producing or revising text, documentation and communication, including translation, localization, creative writing, technical writing and interface copy.',
  'visual design': 'Graphic communication, typography, branding, illustration, printed or digital layouts, packaging graphics, signage and visual storytelling.',
  'images and photography': 'Creating, capturing, editing, converting, optimizing or organizing raster and vector images, photographs and visual assets.',
  'video and animation': 'Producing, editing, animating, compositing, rendering, captioning or delivering moving-image content.',
  '3D and spatial design': 'Creating or manipulating 3D geometry, scenes, materials, rendering, CAD, BIM, spatial media and simulations.',
  'audio and music': 'Creating, arranging, recording, editing, analyzing, mixing, restoring or delivering music, sound, speech and audio assets.',
  'games and interactive media': 'Designing, building, testing or producing digital games, tabletop games, interactive fiction, playable simulations and interactive media.',
  'marketing and sales': 'Researching markets and audiences, positioning offers, creating persuasive campaigns, acquiring customers and managing sales or commercial conversion.',
  'business and management': 'Planning and running products, projects, organizations, services, people, customers, procurement and business processes, including service quality improvement.',
  'finance and accounting': 'Accounting, financial reporting, budgeting, payments, valuation, investment analysis and management of financial risk or financial controls.',
  'law and governance': 'Researching or documenting law, regulation, contracts, rights, policies, institutional governance and compliance obligations.',
  'science and research': 'Scientific, mathematical or scholarly investigation, research methods, experiments, laboratory work, evidence synthesis, computation and reproducibility.',
  'engineering and hardware': 'Designing, implementing or maintaining physical and electronic systems, embedded hardware and firmware, engineering analyses and manufacturing technology.',
  'health and wellbeing': 'Health, clinical work, medical research, nutrition, physical training, wellbeing, care services, healthcare data and healthcare quality.',
  'education and learning': 'Designing, delivering, assessing or improving teaching, study, training, educational content and learning systems.',
  'personal planning and communication': 'Organizing personal or household goals, schedules, travel, events, correspondence, career decisions and interpersonal communication.',
  'culture and humanities': 'Investigating or interpreting history, language, culture, arts, philosophy, society, archives and humanistic scholarship.',
  'practical and outdoor activities': 'Hands-on household, food, craft, land, farm, vehicle, animal and outdoor activities, their logistics and maintenance.',
  'UI and interaction design': 'Designing interfaces, controls, layouts, navigation, interaction flows and prototypes for digital software or interactive physical products; includes design-to-code work.',
  'UX research and design': 'Studying and improving how people use products, spaces or services, including research, usability, journeys, information architecture, content and experience design.',
  'design systems and accessibility': 'Reusable interface design systems and making digital content, software, media or learning materials accessible through components, standards and assistive interaction.',
  'physical design': 'Designing or prototyping the form, ergonomics, spaces, user experience and usability of tangible products, buildings, environments, clothing or manufactured objects.',
  'physical product testing and quality': 'Validating physical prototypes, components and finished products, including performance, durability, environmental exposure, electrical safety, compliance and reliability. Includes embedded products but not software-only tests.',
  'manufacturing quality': 'Controlling the quality of physical production and suppliers through inspections, metrology, sampling, process validation, defect prevention, audits and corrective actions.',
};

// Additional parents keep shared activities reachable without duplicating canonical categories.
const sharedFamilies: Array<{ labels: readonly CategoryLabel[]; parents: readonly GroupLabel[] }> = [
  { labels: groups['software testing and quality'], parents: ['software development'] },
  { labels: groups['UI and interaction design'], parents: ['software development'] },
  { labels: groups['UX research and design'], parents: ['physical design', 'business and management'] },
  { labels: groups['design systems and accessibility'], parents: ['UI and interaction design', 'software development'] },
  { labels: groups['physical product testing and quality'], parents: ['engineering and hardware', 'physical design'] },
  { labels: groups['manufacturing quality'], parents: ['engineering and hardware', 'business and management'] },
  { labels: ['UX writing', 'Content adaptation', 'Plain-language rewriting'], parents: ['UX research and design', 'UI and interaction design'] },
  { labels: ['Technical writing', 'API documentation', 'Release notes', 'Documentation maintenance', 'Technical documentation generation'], parents: ['software development', 'documents and office work'] },
  { labels: ['Scientific editing', 'Peer review writing', 'Research abstracts', 'Academic writing', 'Grant writing'], parents: ['science and research', 'documents and office work'] },
  { labels: ['Business writing', 'Executive summaries', 'Resume writing', 'Newsletter writing', 'Speechwriting'], parents: ['documents and office work', 'business and management'] },
  { labels: ['Copywriting', 'Landing page copy', 'Content strategy', 'Content calendars', 'Brand messaging', 'Persuasive writing'], parents: ['writing and languages'] },
  { labels: ['Translation', 'Localization', 'Transcreation', 'Terminology management', 'Internationalized application development'], parents: ['software development'] },
  { labels: ['Subtitling translation', 'Dialogue writing', 'Screenwriting'], parents: ['video and animation'] },
  { labels: ['Localization testing', 'Game localization', 'Video localization', 'Cultural translation', 'Legal translation'], parents: ['writing and languages'] },
  { labels: ['Accessibility testing', 'Accessibility acceptance criteria'], parents: ['software testing and quality', 'design systems and accessibility'] },
  { labels: ['Presentation accessibility', 'Document accessibility', 'Accessible learning materials', 'Accessible typography', 'Accessible data visualization', 'Health accessibility'], parents: ['design systems and accessibility'] },
  { labels: ['Video accessibility', 'Audio accessibility', 'Game accessibility', 'Accessible multimedia design', 'Subtitles and captions'], parents: ['design systems and accessibility'] },
  { labels: ['Universal physical access design', 'Ergonomic design', 'Inclusive experience design'], parents: ['UX research and design', 'physical design'] },
  { labels: ['Design-to-code implementation', 'Component API design', 'Component libraries', 'State management'], parents: ['UI and interaction design', 'design systems and accessibility'] },
  { labels: ['Game UI design', 'Conversational experience design', 'Voice interface design', 'Spatial interaction design'], parents: ['UI and interaction design', 'UX research and design'] },
  { labels: ['Graphic design', 'Illustration', 'Icon design', 'Vector graphics', 'Digital painting', 'Concept art', 'Character illustration', 'Pixel art', 'Sprite creation'], parents: ['visual design', 'images and photography'] },
  { labels: ['Brand identity', 'Brand guidelines', 'Brand strategy', 'Campaign design', 'Social media graphics', 'Art direction', 'Product positioning'], parents: ['marketing and sales', 'visual design'] },
  { labels: ['Typography', 'Visual hierarchy', 'Page composition', 'Editorial design', 'Publication design', 'Print production', 'Presentation visual identity', 'Slide layout'], parents: ['documents and office work', 'visual design'] },
  { labels: ['Packaging design', 'Environmental graphics', 'Signage design', 'Wayfinding', 'Lighting design', 'Exhibition planning', 'Museum interpretation'], parents: ['physical design', 'visual design'] },
  { labels: ['Data graphic design', 'Infographic design', 'Data storytelling', 'Chart selection', 'Chart interface design', 'Presentation charts', 'Spreadsheet charts'], parents: ['data analysis', 'visual design'] },
  { labels: ['3D printing', 'CAD modeling', 'Building information modeling', 'Parametric modeling', 'Engineering drawings', 'Photogrammetry', '3D scanning', 'Digital fabrication'], parents: ['3D and spatial design', 'engineering and hardware', 'physical design'] },
  { labels: ['Architectural visualization', '3D product visualization', 'Furniture design', 'Architectural design', 'Interior design', 'Landscape design'], parents: ['3D and spatial design', 'physical design'] },
  { labels: ['Product photography', 'Architectural photography', 'Photo color grading', 'Color correction'], parents: ['visual design'] },
  { labels: ['Animation', 'Character animation', 'Rigging', 'Facial animation', 'Camera animation', 'Physics simulation', 'Particle systems', 'Cloth simulation', 'Animation retargeting'], parents: ['3D and spatial design', 'video and animation', 'games and interactive media'] },
  { labels: ['Motion graphics', 'Animation timing', 'Animated interface assets', 'Microinteraction design', 'Interface motion design', 'Reduced motion design'], parents: ['UI and interaction design', 'video and animation'] },
  { labels: ['Game assets', 'Game modding', 'Procedural level generation', 'Character modeling', 'Environment modeling', 'Texture creation', '3D asset optimization'], parents: ['games and interactive media', '3D and spatial design'] },
  { labels: ['Video scripting', 'Storyboarding', 'Video production', 'Explainer videos', 'Product demo videos', 'Ad creative testing'], parents: ['marketing and sales', 'video and animation'] },
  { labels: ['Game audio', 'Film scoring', 'Jingle production', 'Sound design', 'Video audio synchronization'], parents: ['audio and music', 'video and animation', 'games and interactive media'] },
  { labels: ['Podcast production', 'Audio transcription', 'Dialogue editing', 'Subtitles and captions', 'Screen recordings'], parents: ['video and animation', 'audio and music'] },
  { labels: ['Speech recognition', 'Speech synthesis', 'Voice synthesis', 'Natural language processing', 'Optical character recognition', 'Document understanding', 'Text summarization', 'Translation systems'], parents: ['AI and automation'] },
  { labels: ['Machine learning', 'AI model evaluation', 'Model fine-tuning', 'AI benchmark design', 'Dataset labeling', 'Synthetic data generation', 'Computer vision'], parents: ['science and research', 'data analysis'] },
  { labels: ['Database design', 'SQL queries', 'Schema evolution', 'Data modeling', 'Database transactions', 'Query optimization', 'Search implementation'], parents: ['software development', 'data engineering'] },
  { labels: ['Data cleaning', 'Data validation', 'Data integration', 'Data export', 'Dataset preparation', 'Data deduplication', 'Entity resolution'], parents: ['data analysis', 'science and research'] },
  { labels: ['Data pipelines', 'Data orchestration', 'Stream processing', 'Event ingestion', 'Workflow automation', 'Scheduled automation', 'Email automation'], parents: ['AI and automation'] },
  { labels: ['Backup and recovery', 'Database administration', 'Database replication', 'Database sharding', 'Data warehouses', 'Model deployment', 'Vector databases'], parents: ['infrastructure and operations'] },
  { labels: ['Embeddings', 'Semantic search', 'Retrieval-augmented generation', 'Knowledge graphs', 'Document indexing', 'Structured data extraction'], parents: ['data engineering', 'AI and automation'] },
  { labels: ['Document extraction', 'PDF text extraction', 'CSV processing', 'Spreadsheet formulas', 'Spreadsheet pivots', 'Spreadsheet modeling', 'Spreadsheet auditing'], parents: ['data analysis', 'data engineering'] },
  { labels: ['Statistical analysis', 'Hypothesis testing', 'Causal inference', 'Bayesian analysis', 'Regression analysis', 'Experiment design', 'Experimental design', 'Survey analysis', 'Time-series analysis', 'Scientific visualization'], parents: ['data analysis', 'science and research'] },
  { labels: ['Numerical methods', 'Optimization theory', 'Scientific computing', 'Research software engineering', 'Simulation modeling', 'Signal processing', 'Control systems', 'Finite element analysis', 'Thermal analysis', 'Fluid dynamics'], parents: ['science and research', 'engineering and hardware'] },
  { labels: ['Geospatial analysis', 'Remote sensing', 'Climate science', 'Meteorology', 'Environmental science', 'Ecology'], parents: ['data analysis', 'science and research', 'practical and outdoor activities'] },
  { labels: ['Clinical trial analysis', 'Medical research', 'Medical literature analysis', 'Clinical research protocols', 'Nutrition research', 'Epidemiology', 'Neuroscience', 'Psychology research'], parents: ['science and research', 'health and wellbeing'] },
  { labels: ['Healthcare data analysis', 'Population health analysis', 'Sports performance analysis', 'Financial analytics', 'Financial statement analysis', 'Portfolio analysis', 'Econometrics'], parents: ['data analysis'] },
  { labels: ['Customer segmentation', 'Attribution analysis', 'Marketing attribution', 'Marketing measurement', 'Pricing analysis', 'A/B test evaluation', 'Conversion optimization', 'Funnel analysis', 'Cohort analysis', 'Retention analysis'], parents: ['marketing and sales', 'data analysis'] },
  { labels: ['Product analytics', 'Metric definition', 'Experiment analysis', 'Dashboard creation', 'Forecasting', 'Operational analytics', 'Business intelligence'], parents: ['business and management', 'data analysis'] },
  { labels: ['Financial modeling', 'Budgeting', 'Personal budgeting', 'Cash flow planning', 'Scenario modeling', 'Sensitivity analysis', 'Cost accounting', 'Unit economics'], parents: ['finance and accounting', 'business and management'] },
  { labels: ['Billing and invoicing', 'Payment integration', 'Subscription accounting', 'Revenue recognition', 'Payroll accounting', 'Expense management'], parents: ['finance and accounting', 'business and management'] },
  { labels: ['Root cause and corrective action', 'Process improvement', 'Reliability engineering'], parents: ['business and management', 'manufacturing quality', 'physical product testing and quality'] },
  { labels: ['Reliability engineering', 'Hardware validation', 'Firmware development', 'Embedded systems', 'Internet of things systems', 'Hardware prototyping', 'Physical prototype validation'], parents: ['engineering and hardware', 'physical product testing and quality'] },
  { labels: ['Reliability engineering', 'Site reliability engineering', 'Disaster recovery', 'Software deployment', 'Continuous integration', 'Release engineering'], parents: ['infrastructure and operations', 'software development'] },
  { labels: ['Statistical process control', 'Manufacturing process capability', 'Production yield improvement', 'Measurement system analysis', 'Manufacturing sampling plans', 'Physical product failure analysis'], parents: ['data analysis', 'manufacturing quality'] },
  { labels: ['Manufacturing quality control', 'Non-destructive testing', 'Destructive material testing', 'Physical product safety testing', 'Electrical safety testing', 'Electromagnetic compatibility testing'], parents: ['engineering and hardware', 'manufacturing quality'] },
  { labels: ['Software unit testing', 'Software security testing', 'Vulnerability analysis', 'Penetration testing', 'Security fix verification', 'Security testing automation', 'Fuzz testing'], parents: ['software testing and quality', 'security and privacy'] },
  { labels: ['Authentication', 'Authorization', 'OAuth integration', 'Single sign-on', 'Session security', 'Secure coding', 'API security'], parents: ['software development'] },
  { labels: ['Cloud security', 'Container security', 'Network security', 'Secrets management', 'Security monitoring', 'Security incident response'], parents: ['infrastructure and operations'] },
  { labels: ['Privacy assessment', 'Compliance assessment', 'Privacy law research', 'Data retention policy', 'Data processing agreements', 'Privacy notice drafting', 'Security policy design'], parents: ['law and governance', 'security and privacy'] },
  { labels: ['Data governance', 'Data lineage', 'Data retention policy', 'Data anonymization', 'Data access control', 'Privacy engineering'], parents: ['data engineering', 'security and privacy'] },
  { labels: ['Policy drafting', 'Records management', 'Corporate governance', 'Governance documentation', 'Due diligence documentation', 'Vendor evaluation'], parents: ['business and management', 'law and governance'] },
  { labels: ['Product discovery', 'Product management', 'Requirements analysis', 'User story writing', 'Customer feedback analysis', 'Service design'], parents: ['UX research and design', 'physical design'] },
  { labels: ['Requirements analysis', 'Technical specification writing', 'Systems engineering', 'Product manufacturability', 'Maintenance planning'], parents: ['engineering and hardware', 'business and management'] },
  { labels: ['Market research', 'Audience research', 'Competitive analysis', 'Competitive strategy', 'Business model design'], parents: ['business and management', 'marketing and sales'] },
  { labels: ['Qualitative research', 'Ethnographic research', 'User interviews', 'Contextual inquiry', 'Diary studies', 'Survey analysis', 'Public opinion research', 'Research ethics'], parents: ['UX research and design', 'science and research', 'culture and humanities'] },
  { labels: ['Literature reviews', 'Evidence synthesis', 'Meta-analysis', 'Research design', 'Research data management'], parents: ['science and research', 'health and wellbeing', 'education and learning', 'culture and humanities'] },
  { labels: ['Instructional design', 'Course design', 'E-learning development', 'Learning evaluation', 'Learning analytics', 'Educational games', 'Educational simulation', 'Serious games'], parents: ['education and learning', 'UX research and design'] },
  { labels: ['Educational games', 'Educational simulation', 'Serious games', 'Tabletop games', 'Simulation design'], parents: ['education and learning', 'games and interactive media'] },
  { labels: ['Programming tutoring', 'Learning platform administration', 'E-learning development', 'Adaptive learning'], parents: ['software development', 'education and learning'] },
  { labels: ['Corporate training', 'Training needs analysis', 'Skills assessment', 'Workshop design', 'Employee onboarding', 'Security awareness training', 'Health education'], parents: ['education and learning', 'business and management'] },
  { labels: ['Healthcare quality improvement', 'Health service planning', 'Care coordination'], parents: ['business and management', 'health and wellbeing'] },
  { labels: ['Learning analytics', 'Student progress tracking', 'Learning evaluation', 'Assessment design'], parents: ['data analysis', 'education and learning'] },
  { labels: ['Literary analysis', 'Film criticism', 'Rhetorical analysis', 'Textual criticism', 'Linguistics', 'Oral history', 'Historical source analysis'], parents: ['writing and languages', 'culture and humanities'] },
  { labels: ['Digital humanities', 'Archives research', 'Genealogy', 'Cultural heritage documentation'], parents: ['science and research', 'data engineering'] },
  { labels: ['Negotiation', 'Public speaking', 'Conflict resolution communication', 'Interview preparation', 'Email drafting', 'Meeting facilitation'], parents: ['business and management', 'personal planning and communication'] },
  { labels: ['Meal planning', 'Nutrition', 'Food safety education', 'Recipe development', 'Sports training', 'Outdoor recreation'], parents: ['health and wellbeing', 'practical and outdoor activities'] },
  { labels: ['Landscape gardening', 'Irrigation planning', 'Home energy planning', 'Home improvement', 'Furniture restoration', 'Woodworking', 'Metalworking', 'Pattern making', 'Sewing', 'Jewelry making'], parents: ['physical design', 'practical and outdoor activities'] },
  { labels: ['Vehicle maintenance', 'Cycling maintenance', 'Home repair planning', 'Property maintenance', 'Digital fabrication'], parents: ['engineering and hardware', 'practical and outdoor activities'] },
  { labels: ['Supply chain planning', 'Inventory management', 'Farm operations planning', 'Event planning', 'Volunteer coordination', 'Travel logistics'], parents: ['business and management', 'practical and outdoor activities'] },
];

const slug = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-');
export const CATEGORY_GROUPS: CategoryGroup[] = Object.keys(groups).map((label) => ({
  label, description: descriptions[label as GroupLabel],
}));
export const CATEGORIES: Category[] = Object.entries(groups).flatMap(([primary, labels]) =>
  labels.map((label) => ({
    id: slug(label), label,
    groups: [...new Set([primary, ...sharedFamilies.filter((family) => family.labels.includes(label)).flatMap((family) => family.parents)])],
  })));
